# Copyright 2026 Terrene Foundation
# SPDX-License-Identifier: Apache-2.0
"""
# ════════════════════════════════════════════════════════════════════════
# MLFP04 — Exercise 6.3: LDA — Probabilistic Topic Modelling
# ════════════════════════════════════════════════════════════════════════
#
# WHAT YOU'LL LEARN:
#   - Explain LDA as a generative model: Dirichlet -> topic -> word
#   - Fit LDA and read topic-word and document-topic distributions
#   - Fit LDA on word COUNTS and measure HELD-OUT perplexity across K
#   - Read a document's mixed-membership topic distribution
#   - Apply LDA to news routing where stories span sections
#
# PREREQUISITES: Exercise 6.2 (NMF), basic probability (Dirichlet).
#
# ESTIMATED TIME: ~35 min
#
# TASKS:
#   1. Theory — generative story, Dirichlet prior, mixed membership
#   2. Build — bag-of-words counts + train/held-out split
#   3. Train — held-out perplexity sweep across K
#   4. Visualise — per-topic top words, mixed-membership example
#   5. Apply — media-monitoring story routing
# ════════════════════════════════════════════════════════════════════════
"""
from __future__ import annotations

import numpy as np
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer

from kailash_ml import ModelVisualizer

from shared.mlfp04.ex_6 import (
    NEWS_STOP_WORDS,
    OUTPUT_DIR,
    compute_npmi,
    corpus_as_lists,
    load_corpus,
    print_scenario,
)
from shared.mlfp004 import create_visualizer


# ════════════════════════════════════════════════════════════════════════
# THEORY — LDA as a Generative Model
# ════════════════════════════════════════════════════════════════════════
# Latent Dirichlet Allocation (Blei, Ng, Jordan 2003) assumes every
# document was generated by this process:
#
#   1. For each document d, draw topic proportions:
#        theta_d ~ Dirichlet(alpha)
#
#   2. For each word position in d:
#        a. Draw a topic:  z ~ Categorical(theta_d)
#        b. Draw a word:   w ~ Categorical(beta_z)
#
# The Dirichlet prior alpha controls sparsity: small alpha -> documents
# concentrate on a few topics, large alpha -> documents spread across
# many topics. beta is the topic-word distribution we care about.
#
# KEY DIFFERENCE FROM NMF: LDA is PROBABILISTIC. theta_d is a real
# probability distribution that sums to 1, not just a weight vector.
# This means "document 17 is 62% markets, 23% technology, 15% world
# politics" is a meaningful statement.
#
# MIXED MEMBERSHIP is why LDA matters for some use cases: a story about
# a tech company's earnings genuinely belongs to TWO topics at once.
# NMF's W also has several non-zero weights per document, but they are
# unnormalised reconstruction weights, so LDA's proportions are the
# directly interpretable version of the overlap.
#
# INPUT MUST BE COUNTS. LDA's generative story draws whole WORDS, so it
# is fitted on a bag-of-words count matrix (CountVectorizer), not on
# TF-IDF weights — TF-IDF values are not word counts.
#
# PERPLEXITY MUST BE HELD OUT. Perplexity on the documents the model was
# trained on always flatters bigger K. We hold out 20% of documents and
# measure perplexity on them: lower = the model predicts unseen text
# better.


# ════════════════════════════════════════════════════════════════════════
# TASK 2 — BUILD: vectorise and fit LDA
# ════════════════════════════════════════════════════════════════════════

corpus_df = load_corpus()
documents, categories = corpus_as_lists(corpus_df)
print(f"Corpus: {len(documents):,} documents")

# TODO: LDA needs word COUNTS. Build a CountVectorizer with
# max_features=3000, stop_words=NEWS_STOP_WORDS, max_df=0.95, min_df=3,
# then fit_transform the documents.
vectorizer = ____
X = ____
vocab = vectorizer.get_feature_names_out()

# 80/20 document split — the held-out 20% is only used to score perplexity
rng = np.random.default_rng(42)
perm = rng.permutation(X.shape[0])
n_train = int(0.8 * X.shape[0])
train_idx, heldout_idx = perm[:n_train], perm[n_train:]
X_train, X_heldout = X[train_idx], X[heldout_idx]
print(
    f"Count matrix: {X.shape}; train docs {X_train.shape[0]}, "
    f"held-out docs {X_heldout.shape[0]}"
)


# ════════════════════════════════════════════════════════════════════════
# TASK 3 — TRAIN: perplexity sweep
# ════════════════════════════════════════════════════════════════════════

print("\n" + "=" * 70)
print("  LDA Perplexity Sweep")
print("=" * 70)
print("Perplexity on the 20% HELD-OUT documents — lower = better prediction")
print("of unseen text")
print()

k_grid = [5, 8, 10, 12, 15]
results = {}
for k in k_grid:
    # TODO: LatentDirichletAllocation with n_components=k, random_state=42,
    # max_iter=20, learning_method="online", batch_size=128. Fit it on the
    # TRAIN documents only, then score perplexity on the HELD-OUT ones.
    lda = ____
    ____
    perp = ____
    results[k] = {"model": lda, "perplexity": float(perp)}
    print(f"  K={k:>2}: held-out perplexity = {perp:,.0f}")

best_k = min(k_grid, key=lambda k: results[k]["perplexity"])
print(f"\n  Lowest held-out perplexity at K={best_k}")

# Use K=10 for detailed analysis
K = 10
lda_model = results[K]["model"]
# TODO: topic proportions for EVERY document (rows sum to 1).
# Hint: a fitted LDA model's .transform(...)
doc_topics = ____
dominant = doc_topics.argmax(axis=1)

topic_words: list[list[str]] = []
print(f"\nTopic words for K={K}:")
for t in range(K):
    top_idx = lda_model.components_[t].argsort()[-8:][::-1]
    words = [vocab[i] for i in top_idx]
    topic_words.append(words)
    n_docs_t = int((dominant == t).sum())
    print(f"  Topic {t}: {', '.join(words)} (n={n_docs_t})")


# ── Checkpoint 1 ─────────────────────────────────────────────────────
assert doc_topics.shape == (
    len(documents),
    K,
), "Task 3: document-topic matrix shape mismatch"
row_sums = doc_topics.sum(axis=1)
assert np.allclose(row_sums, 1.0, atol=1e-2), "Task 3: LDA rows must sum to 1"
print("\n[ok] Checkpoint 1 passed — LDA perplexity sweep + topics\n")


# ════════════════════════════════════════════════════════════════════════
# TASK 4 — VISUALISE: mixed membership + NPMI coherence
# ════════════════════════════════════════════════════════════════════════

# Find a document with genuinely mixed membership (max prob < 0.5)
mixed_idx = -1
for i in range(len(documents)):
    # TODO: a document is "mixed" when its top topic has probability < 0.5
    # AND at least 2 topics have probability > 0.1.
    if ____:
        mixed_idx = i
        break

if mixed_idx >= 0:
    print("\n" + "=" * 70)
    print(f"  Mixed-membership example — document #{mixed_idx}")
    print("=" * 70)
    print(f"Text (first 200 chars): {documents[mixed_idx][:200]}...")
    print(f"\nTopic distribution:")
    for t in np.argsort(-doc_topics[mixed_idx])[:5]:
        prob = doc_topics[mixed_idx, t]
        if prob < 0.02:
            break
        bar = "#" * int(prob * 40)
        print(f"  Topic {t} ({prob:5.1%}) {bar} — {', '.join(topic_words[t][:5])}")

# TODO: NPMI coherence per topic, tokenising with the vectoriser's analyser.
coherences = ____
mean_npmi = float(np.mean(coherences))
print(f"\nLDA mean NPMI coherence: {mean_npmi:+.4f}")

viz = create_visualizer()

# Perplexity curve
perp_data = {f"K={k}": {"perplexity": results[k]["perplexity"]} for k in k_grid}
fig_perp = viz.metric_comparison(perp_data)
fig_perp.update_layout(title="LDA Held-Out Perplexity vs Number of Topics")
fig_perp.write_html(str(OUTPUT_DIR / "ex6_3_lda_perplexity.html"))

# Coherence bars
coh_data = {f"Topic_{i}": {"NPMI": float(c)} for i, c in enumerate(coherences)}
fig_coh = viz.metric_comparison(coh_data)
fig_coh.update_layout(title="LDA Topic Coherence (NPMI)")
fig_coh.write_html(str(OUTPUT_DIR / "ex6_3_lda_coherence.html"))

print(f"\nSaved: {OUTPUT_DIR}/ex6_3_lda_perplexity.html")
print(f"Saved: {OUTPUT_DIR}/ex6_3_lda_coherence.html")


# ── Checkpoint 2 ─────────────────────────────────────────────────────
assert (
    results[5]["perplexity"] != results[15]["perplexity"]
), "Task 4: perplexity must change with K"
assert len(coherences) == K, "Task 4: one NPMI per topic"
print("\n[ok] Checkpoint 2 passed — mixed-membership example and visualisations\n")


# ════════════════════════════════════════════════════════════════════════
# TASK 5 — APPLY: Media-Monitoring Story Routing
# ════════════════════════════════════════════════════════════════════════

print_scenario("lda_topics")
print(
    """
WHY LDA FOR STORY ROUTING:
  - A story about a tech company's quarterly earnings is GENUINELY a
    mixed case. Routing on any single "top topic" (LDA's argmax or
    NMF's largest weight) sends it to one desk only; LDA's proportions
    say e.g. "60% markets, 30% technology", so the routing system can
    send a copy to BOTH desks above a threshold.
  - LDA's sparsity prior (alpha) can be tuned: low alpha forces
    documents to concentrate on 1-2 topics (good for clean routing);
    high alpha produces smoother distributions (good for analytics).
  - The held-out perplexity sweep gives a defensible answer to "why
    this many topics" — pair it with NPMI and a human read of the
    topics, because the lowest perplexity is not always the most
    readable set.

ILLUSTRATIVE ARITHMETIC (assumptions, not measured figures):
  - Assume ~60K stories/year, 15% of them relevant to two desks, and
    that a missed copy costs an analyst 20 minutes to recover later:
    dual routing avoids ~3,000 analyst-hours a year
    (60K x 15% x 20 min).
"""
)


# ════════════════════════════════════════════════════════════════════════
# REFLECTION
# ════════════════════════════════════════════════════════════════════════
print("\n" + "=" * 70)
print("  WHAT YOU'VE MASTERED")
print("=" * 70)
print(
    """
  [x] Explained LDA's generative story (Dirichlet -> topic -> word)
  [x] Fit LDA on word counts across multiple K and read a HELD-OUT
      perplexity curve
  [x] Found a document with mixed membership across 2+ topics
  [x] Measured NPMI coherence for LDA topics
  [x] Mapped the technique to media-monitoring story routing

  LDA vs NMF — WHEN TO PICK WHICH:
    NMF:  you need speed, determinism, and a simple dominant-topic tag
    LDA:  you need probabilistic semantics, mixed membership, and
          the ability to say "this doc is 62% topic A, 28% topic B"
          in a defensible way

  Next: 04_bertopic.py — replace word counts with neural sentence
  embeddings so paraphrases that share few words can cluster together.
"""
)
