# Copyright 2026 Terrene Foundation
# SPDX-License-Identifier: Apache-2.0
"""
MLFP06 — Assessment Task 2: RAG Pipeline with Evaluation (Reference Solution)

Reference implementation. Withheld from students. Verified to pass grader.py.
Dense retrieval (nomic-embed-text + cosine) over a fixed SQuAD corpus, then a
grounded answer generated by the local Ollama LLM at temperature 0.
"""
from __future__ import annotations

import asyncio
import math

import polars as pl

from shared import MLFPDataLoader
from shared.mlfp06._ollama_bootstrap import (
    make_delegate,
    make_embedder,
    run_delegate_text,
)

TOP_K = 3
N_CORPUS = 30
N_QUERIES = 6


_STOP = {
    "the",
    "a",
    "an",
    "of",
    "to",
    "in",
    "on",
    "and",
    "or",
    "for",
    "is",
    "are",
    "was",
    "were",
    "by",
    "at",
    "as",
    "with",
    "that",
    "this",
    "near",
    "present",
    "day",
}


def _content_tokens(s: str) -> list[str]:
    import re

    return [
        t
        for t in re.sub(r"[^a-z0-9 ]", " ", str(s).lower()).split()
        if t not in _STOP and len(t) >= 3
    ]


def build_corpus_and_questions() -> tuple[list[str], list[str]]:
    """Deterministically build the retrieval corpus + the evaluation questions.

    The corpus is the first N_CORPUS unique answerable SQuAD contexts. The
    questions are the first N_QUERIES questions whose gold answer is a short,
    distinctive fact (1–3 content tokens) drawn from a context in the corpus.
    Pure function of the parquet — no randomness.
    """
    df = MLFPDataLoader().load("mlfp06", "squad/squad_v2_300.parquet")
    answerable = df.filter(
        (pl.col("answer").is_not_null()) & (pl.col("answer").str.len_chars() > 0)
    )
    seen: dict[str, int] = {}
    corpus: list[str] = []
    questions: list[str] = []
    for row in answerable.iter_rows(named=True):
        ctx = row["text"]
        if ctx not in seen:
            seen[ctx] = len(corpus)
            corpus.append(ctx)
        if len(questions) < N_QUERIES and row["question"]:
            if 1 <= len(_content_tokens(row["answer"])) <= 3:
                questions.append(row["question"])
        if len(corpus) >= N_CORPUS and len(questions) >= N_QUERIES:
            break
    return corpus, questions


def _cosine(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(x * x for x in b))
    return dot / (na * nb) if na and nb else 0.0


async def _run() -> dict:
    corpus, questions = build_corpus_and_questions()

    embedder = make_embedder(model="nomic-embed-text")
    corpus_vecs = await embedder.embed(corpus)
    query_vecs = await embedder.embed(questions)

    retrieved: list[list[int]] = []
    answers: list[str] = []
    for q, qv in zip(questions, query_vecs):
        ranked = sorted(
            ((_cosine(qv, cv), i) for i, cv in enumerate(corpus_vecs)),
            reverse=True,
        )
        top = [i for _, i in ranked[:TOP_K]]
        retrieved.append(top)

        context = "\n\n".join(corpus[i][:1200] for i in top)
        prompt = (
            "Answer the question using ONLY the context below. Be concise — "
            "give just the fact, not a sentence of preamble.\n\n"
            f"Context:\n{context}\n\nQuestion: {q}\nAnswer:"
        )
        delegate = make_delegate(model="llama3.2:3b", temperature=0.0, max_tokens=256)
        text, _usage, _elapsed = await run_delegate_text(delegate, prompt)
        answers.append(text.strip())

    return {"retrieved": retrieved, "answers": answers}


def solve() -> dict:
    """Run the RAG pipeline over the fixed SQuAD corpus.

    Returns {"retrieved": list[list[int]], "answers": list[str]} with one
    entry per evaluation question (top-3 doc indices + the grounded answer).
    """
    return asyncio.run(_run())


if __name__ == "__main__":
    out = solve()
    for i, (r, a) in enumerate(zip(out["retrieved"], out["answers"])):
        print(f"Q{i}: top3={r}  answer={a[:70]!r}")
